# -*- coding: utf-8 -*-
"""PRO-124-Project-Boilerplate-Code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zyFpXcTMsM6kc96j4-VbhjYnWReGnNLY

## Print Elements of Array

**Problem**: Given 1X1 Array:

```
arr_1d = [53, 78, 90, 12, 15, 65, 44, 32, 29, 36]
```

1. Print 3rd and 9th element of the array.
2. Change  3rd and 9th element to 100.
"""

# write code here

"""## Update Diagonal Elements of Multidimensional Array

**Problem**: Given a 3x3 array, change all the diagonal elements of the matrix to 0.

```

arr_2d = [[1,2,3],
          [4,5,6],
          [7,8,9]]
```
"""

#Write code here

"""## Numbers of Rows & Column

**Problem**: Write a program to find the number of rows and columns present in the matrix given below.
Note: Initialize the matrix using NumPy.

```
 A= [[9,5,6,1,-2],
    [3,-8,1,2,0],
    [6,9,3,3,5]]
```
"""

# write code here

"""## Scalar Multiplication

**Problem**: Print each element of the following matrix. Initialize the matrix using NumPy.  <br />
Also, multiply the matrix with n = 150 and print the matrix after multiplication.
   
```
 B=[[-8,0,2,4],[5,2,-1,7]]
```
"""

